# Generated by Django 4.0.1 on 2022-01-16 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditurereceipt',
            name='by_user',
        ),
        migrations.RemoveField(
            model_name='expenditurereceipt',
            name='expenditure_title',
        ),
        migrations.AddField(
            model_name='expenditurereceipt',
            name='extracted_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenditurereceipt',
            name='for_expenditure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.expenditure'),
        ),
    ]
