# Generated by Django 4.0.1 on 2022-01-17 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_remove_expenditurereceipt_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditurereceipt',
            name='by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
