# Generated by Django 4.0.1 on 2022-01-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
